// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

RWTexture2D<float4> Result;

float Radius;
StructuredBuffer<float2> Points;
int PointCount;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float sum = 0;
    for (int i = 0; i < PointCount; i++)
    {
        float d = distance(Points[i], id.xy);
        sum = max(1 - (d / Radius), sum);
    }

    sum = saturate(sum);

    Result[id.xy] = float4(sum, sum, sum, 1);
}
